version: '3.1'

services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: guiahumanas
      #MYSQL_ROOT_PASSWORD: rootpassword
      #MYSQL_USER: user
      #MYSQL_PASSWORD: userpassword

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin_container
      environment:
        PMA_HOST: mysql
        PMA_PORT: 3306
        MYSQL_ROOT_PASSWORD: rootpassword
      ports:
        - "8080:80"

